name: Documentation

on:
    workflow_dispatch:
    push:
        paths:
            - "docs/**"
            - "sonolink/**"
        branches: [main]

    pull_request:
        paths:
            - "docs/**"
            - "sonolink/**"

    schedule:
        - cron: "0 0 * * *"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    docs:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        timeout-minutes: 15
        if: github.actor != 'renovate[bot]'
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
              with:
                  persist-credentials: false
            - name: Set up Python
              uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
              with:
                  python-version: "3.13"
                  cache: "pip"
                  check-latest: true

            - name: Install library and dependencies
              run: |
                  python -m pip install -U pip
                  pip install ".[docs]"

            - name: Compile Docs
              run: |
                  cd docs
                  make html
